package com.it.dao;

import com.it.po.ReaderCard;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ReaderCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    int insert(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    int insertSelective(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    ReaderCard selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    int updateByPrimaryKeySelective(ReaderCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reader_card
     *
     * @mbggenerated Tue Dec 08 15:59:31 CST 2020
     */
    int updateByPrimaryKey(ReaderCard record);

    /**
     * 查询全部图书列表
     */
    List<ReaderCard> queryReaderCardAll(ReaderCard readerCard);


    ReaderCard queryUsernamePassword(@Param("username") String username, @Param("password") String password);

}